name: ${project.parent.name}
version: ${project.version}
main: dev.anhcraft.craftkit.internal.CraftKit
api-version: 1.13
softdepend: [Vault]
authors: [anhcraft]
description: ${project.parent.description}
